# Generated by Django 5.1.4 on 2024-12-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('email', models.EmailField(default='user@example.com', max_length=100, unique=True)),
                ('mensagem', models.CharField(max_length=256)),
            ],
        ),
    ]
