# Generated by Django 5.1.4 on 2024-12-09 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_data_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_category_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='formulario.usercategory'),
        ),
    ]
