# Generated by Django 5.1.4 on 2024-12-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0005_alter_userdata_user_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='grau_ensino',
            field=models.CharField(default='Não informado', max_length=100),
        ),
    ]
