# Generated by Django 5.1.4 on 2024-12-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0006_userdata_grau_ensino'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='data_registro',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
