# Generated by Django 5.1.4 on 2024-12-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0008_alter_usercategory_user_data_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercategory',
            name='user_data_category',
            field=models.CharField(choices=[('Engenheiro', 'Engenheiro'), ('Técnologo', 'Técnologo'), ('Advogado', 'Advogado'), ('Empresário', 'Empresário'), ('Professor', 'Professor'), ('Programador', 'Programador'), ('Estudante', 'Estudante'), ('Desocupado', 'Desocupado'), ('Outro', 'Outro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='grau_ensino',
            field=models.CharField(choices=[('Ensino Médio Completo', 'Ensino Médio Completo'), ('Ensino Superior Completo', 'Ensino Superior Completo'), ('Mestre', 'Mestre'), ('Doutor', 'Doutor'), ('Albert Einsten', 'Albert Einsten'), ('Marie Curie', 'Marie Curie'), ('Oppenheimer', 'Oppenheimer'), ('Margaret Hamilton', 'Margaret Hamilton'), ('Outro', 'Outro')], default='Não informado', max_length=100),
        ),
    ]
