# Generated by Django 5.1.4 on 2024-12-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0009_alter_usercategory_user_data_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercategory',
            name='user_data_category',
            field=models.CharField(choices=[('Engenheiro', 'Engenheiro'), ('Tecnologo', 'Tecnologo'), ('Advogado', 'Advogado'), ('Empresário', 'Empresário'), ('Professor', 'Professor'), ('Programador', 'Programador'), ('Estudante', 'Estudante'), ('Outro', 'Outro')], max_length=100),
        ),
    ]
